/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReaderRouteImport } from './routes/reader'
import { Route as ApiPublicAnybookChapterRouteImport } from './routes/api/public/anybook/chapter'
import { Route as ApiPublicAnybookPlanRouteImport } from './routes/api/public/anybook/plan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderRoute = ReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnybookChapterRoute = ApiPublicAnybookChapterRouteImport.update({
  id: '/api/public/anybook/chapter',
  path: '/api/public/anybook/chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnybookPlanRoute = ApiPublicAnybookPlanRouteImport.update({
  id: '/api/public/anybook/plan',
  path: '/api/public/anybook/plan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reader': typeof ReaderRoute
  '/api/public/anybook/chapter': typeof ApiPublicAnybookChapterRoute
  '/api/public/anybook/plan': typeof ApiPublicAnybookPlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reader': typeof ReaderRoute
  '/api/public/anybook/chapter': typeof ApiPublicAnybookChapterRoute
  '/api/public/anybook/plan': typeof ApiPublicAnybookPlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reader': typeof ReaderRoute
  '/api/public/anybook/chapter': typeof ApiPublicAnybookChapterRoute
  '/api/public/anybook/plan': typeof ApiPublicAnybookPlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/reader' | '/api/public/anybook/chapter' | '/api/public/anybook/plan'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/reader' | '/api/public/anybook/chapter' | '/api/public/anybook/plan'
  id:
    | '__root__'
    | '/'
    | '/reader'
    | '/api/public/anybook/chapter'
    | '/api/public/anybook/plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReaderRoute: typeof ReaderRoute
  ApiPublicAnybookChapterRoute: typeof ApiPublicAnybookChapterRoute
  ApiPublicAnybookPlanRoute: typeof ApiPublicAnybookPlanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader': {
      id: '/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof ReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/anybook/chapter': {
      id: '/api/public/anybook/chapter'
      path: '/api/public/anybook/chapter'
      fullPath: '/api/public/anybook/chapter'
      preLoaderRoute: typeof ApiPublicAnybookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/anybook/plan': {
      id: '/api/public/anybook/plan'
      path: '/api/public/anybook/plan'
      fullPath: '/api/public/anybook/plan'
      preLoaderRoute: typeof ApiPublicAnybookPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReaderRoute: ReaderRoute,
  ApiPublicAnybookChapterRoute: ApiPublicAnybookChapterRoute,
  ApiPublicAnybookPlanRoute: ApiPublicAnybookPlanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
